projects:
  X App Lambda:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        region: us-east-1
        apiId: aqzplwrclvh2raifuyzqfkbqmi
        maxDepth: 2
extensions:
  amplify:
    version: 3
